export type ProductCategory = "all" | "books" | "rudraksha" | "home-decor";

export interface Product {
  id: string;
  slug: string;
  name: string;
  category: ProductCategory;
  price: number;
  originalPrice?: number;
  badge?: string;
  badgeColor?: string;
  description: string;
  longDescription: string;
  emoji: string;
  inStock: boolean;
  rating: number;
  reviews: number;
  tags: string[];
}

export const products: Product[] = [
  // ── BOOKS ──────────────────────────────────────────
  {
    id: "b1",
    slug: "shiva-purana-simplified",
    name: "Shiva Purana — Simplified Tamil & English",
    category: "books",
    price: 349,
    originalPrice: 499,
    badge: "Bestseller",
    badgeColor: "#8B5A1A",
    description: "Complete Shiva Purana with Tamil transliteration and English meaning",
    longDescription: "A beautifully printed edition of the sacred Shiva Purana, presented in both Tamil and English for devotees worldwide. Each verse is accompanied by its meaning and spiritual significance.",
    emoji: "📖",
    inStock: true,
    rating: 4.9,
    reviews: 214,
    tags: ["shiva", "purana", "scripture"],
  },
  {
    id: "b2",
    slug: "path-of-thiyanam",
    name: "The Path of Thiyanam — Amma's Teachings",
    category: "books",
    price: 449,
    badge: "New",
    badgeColor: "#C17F4A",
    description: "Amma's discourses on Shaiva meditation practices compiled into one volume",
    longDescription: "This sacred volume contains the essence of Siva Sri Thiyaneswar Amma's teachings on meditation, devotion, and the path to inner stillness. Includes 108 daily practices.",
    emoji: "🧘",
    inStock: true,
    rating: 5.0,
    reviews: 89,
    tags: ["meditation", "teachings", "amma"],
  },
  {
    id: "b3",
    slug: "108-slokas-arunachala",
    name: "108 Slokas of Arunachala — With Meaning",
    category: "books",
    price: 199,
    description: "Sacred hymns to Arunachala hill with Tamil, Sanskrit & English meanings",
    longDescription: "Arunachala, the sacred hill of fire, has inspired countless sages and devotees. This pocket-sized book contains 108 powerful slokas with complete transliteration and meaning.",
    emoji: "⛰️",
    inStock: true,
    rating: 4.8,
    reviews: 156,
    tags: ["arunachala", "slokas", "hymns"],
  },
  {
    id: "b4",
    slug: "tevaram-sacred-hymns",
    name: "Tevaram — Sacred Tamil Hymns of Shiva",
    category: "books",
    price: 599,
    originalPrice: 750,
    badge: "Sacred Text",
    badgeColor: "#7A5C3A",
    description: "The divine Tevaram hymns by the three great Nayanmars in original Tamil",
    longDescription: "The Tevaram is the first seven volumes of the Tirumurai, the sacred canon of Tamil Shaivism. This edition presents the original Tamil verses with transliteration and English commentary.",
    emoji: "🕌",
    inStock: true,
    rating: 4.9,
    reviews: 342,
    tags: ["tevaram", "nayanmars", "tamil"],
  },
  {
    id: "b5",
    slug: "thiruvasagam-guide",
    name: "Thiruvasagam — Heart of Shaiva Bhakti",
    category: "books",
    price: 275,
    description: "Manikkavasagar's immortal devotional verses with commentary",
    longDescription: "Thiruvasagam, meaning 'Sacred Utterances', is one of the most revered texts of Tamil literature and Shaiva devotion. This edition includes scholarly commentary and practice guide.",
    emoji: "📿",
    inStock: true,
    rating: 4.7,
    reviews: 198,
    tags: ["thiruvasagam", "bhakti", "devotional"],
  },

  // ── RUDRAKSHA ─────────────────────────────────────
  {
    id: "r1",
    slug: "pancha-mukhi-mala-108",
    name: "Pancha Mukhi Rudraksha Mala — 108 Beads",
    category: "rudraksha",
    price: 1299,
    originalPrice: 1699,
    badge: "Energized",
    badgeColor: "#6B3A8A",
    description: "Authentic 108-bead Pancha Mukhi mala, energized with Shiva mantras",
    longDescription: "Each bead of this sacred mala has been carefully selected for natural 5-faced (Pancha Mukhi) Rudraksha, strung on red silk thread and energized through Vedic puja rituals at the ashram. Comes with certificate of authenticity.",
    emoji: "📿",
    inStock: true,
    rating: 4.9,
    reviews: 567,
    tags: ["mala", "pancha-mukhi", "energized"],
  },
  {
    id: "r2",
    slug: "eka-mukhi-rudraksha-pendant",
    name: "Eka Mukhi Rudraksha — 1-Face Pendant",
    category: "rudraksha",
    price: 5999,
    badge: "Rare",
    badgeColor: "#8B0000",
    description: "Extremely rare single-faced Rudraksha, believed to be Shiva himself",
    longDescription: "The Eka Mukhi (1-faced) Rudraksha is the rarest and most powerful of all Rudraksha varieties. This pendant comes encased in pure silver with a consecration certificate from the ashram.",
    emoji: "🔮",
    inStock: true,
    rating: 5.0,
    reviews: 43,
    tags: ["eka-mukhi", "rare", "pendant", "silver"],
  },
  {
    id: "r3",
    slug: "gauri-shankar-rudraksha",
    name: "Gauri Shankar Rudraksha — Twin Bead",
    category: "rudraksha",
    price: 2999,
    originalPrice: 3499,
    badge: "Energized",
    badgeColor: "#6B3A8A",
    description: "Two naturally joined Rudraksha beads representing Shiva and Parvati",
    longDescription: "The Gauri Shankar Rudraksha consists of two Rudraksha beads naturally joined together — symbolizing the divine union of Shiva (Shankar) and Parvati (Gauri). Ideal for harmony in relationships and family.",
    emoji: "☯️",
    inStock: true,
    rating: 4.8,
    reviews: 231,
    tags: ["gauri-shankar", "twin", "harmony"],
  },
  {
    id: "r4",
    slug: "rudraksha-bracelet-gold",
    name: "Rudraksha Bracelet — Gold Capped",
    category: "rudraksha",
    price: 1499,
    badge: "Top Rated",
    badgeColor: "#B8860B",
    description: "Authentic Rudraksha beads with 24K gold-plated caps on red thread",
    longDescription: "This elegant bracelet combines 5-faced Rudraksha beads with 24K gold-plated separators, strung on auspicious red thread. Each bracelet is tied with a mantra knot during full moon.",
    emoji: "✨",
    inStock: true,
    rating: 4.9,
    reviews: 389,
    tags: ["bracelet", "gold", "wearable"],
  },
  {
    id: "r5",
    slug: "sapta-mukhi-rudraksha",
    name: "Sapta Mukhi Rudraksha — 7-Face",
    category: "rudraksha",
    price: 1899,
    description: "7-faced Rudraksha associated with Goddess Mahalakshmi and abundance",
    longDescription: "The Sapta Mukhi (7-faced) Rudraksha represents Goddess Mahalakshmi and is known for bringing prosperity, health, and spiritual growth. Each bead is tested for authenticity and energized at the ashram.",
    emoji: "🌟",
    inStock: true,
    rating: 4.7,
    reviews: 178,
    tags: ["sapta-mukhi", "lakshmi", "prosperity"],
  },
  {
    id: "r6",
    slug: "rudraksha-japa-mala-silk",
    name: "Rudraksha Japa Mala — Silk Tassel",
    category: "rudraksha",
    price: 899,
    description: "27-bead counting mala with silk tassel, perfect for mantra japa",
    longDescription: "A beautifully crafted 27-bead Rudraksha japa mala with a hand-stitched silk tassel in saffron. The smaller 27-bead count is traditional for intense japa practice. Comes in a cotton pouch.",
    emoji: "🧵",
    inStock: true,
    rating: 4.6,
    reviews: 445,
    tags: ["japa", "mala", "27-bead", "practice"],
  },

  // ── HOME DECOR ────────────────────────────────────
  {
    id: "h1",
    slug: "brass-karthigai-deepam-lamp",
    name: "Brass Karthigai Deepam Lamp — Tall",
    category: "home-decor",
    price: 1799,
    originalPrice: 2199,
    badge: "Handcrafted",
    badgeColor: "#C17F4A",
    description: "Traditional tall brass lamp hand-crafted in Thiruvannamalai style",
    longDescription: "This magnificent brass lamp is handcrafted by artisans in Thiruvannamalai following the traditional Karthigai Deepam style. Standing 18 inches tall, it holds 5 wicks and is ideal for puja rooms, entrances, or as a centrepiece.",
    emoji: "🪔",
    inStock: true,
    rating: 4.9,
    reviews: 312,
    tags: ["brass", "lamp", "karthigai", "deepam"],
  },
  {
    id: "h2",
    slug: "nataraja-brass-idol",
    name: "Nataraja — Dancing Shiva Brass Idol (8\")",
    category: "home-decor",
    price: 3499,
    badge: "Premium",
    badgeColor: "#8B5A1A",
    description: "Exquisite 8-inch Nataraja idol in solid brass with antique finish",
    longDescription: "This stunning Nataraja idol is cast in solid brass using the traditional lost-wax (Cire Perdue) technique. The 8-inch figure captures every detail of the cosmic dance of Shiva — from the damaru to the ring of fire. Comes with a black lacquered wooden base.",
    emoji: "💃",
    inStock: true,
    rating: 5.0,
    reviews: 187,
    tags: ["nataraja", "shiva", "idol", "brass", "premium"],
  },
  {
    id: "h3",
    slug: "shiva-lingam-black-stone",
    name: "Narmada Shiva Lingam — Black Stone",
    category: "home-decor",
    price: 1999,
    originalPrice: 2499,
    badge: "Sacred",
    badgeColor: "#4A4A8A",
    description: "Natural Narmada river Shiva Lingam, energized at the ashram",
    longDescription: "These sacred Shiva Lingams are sourced directly from the banks of the holy Narmada river — one of the few rivers whose stones are naturally worshipped as Shiva Lingams. Each stone is unique in its natural markings. Energized through Vedic rituals at the ashram before dispatch.",
    emoji: "⚫",
    inStock: true,
    rating: 4.9,
    reviews: 423,
    tags: ["lingam", "narmada", "stone", "sacred"],
  },
  {
    id: "h4",
    slug: "panchamukha-vilakku-brass",
    name: "Panchamukha Vilakku — 5-Flame Brass Lamp",
    category: "home-decor",
    price: 3999,
    badge: "Artisan",
    badgeColor: "#8B5A1A",
    description: "Five-headed traditional brass lamp, symbol of the five elements",
    longDescription: "The Panchamukha (5-headed) Vilakku is a traditional South Indian lamp representing the five elements — earth, water, fire, air, and ether. Crafted in heavy brass with an intricate peacock motif base. A treasured heirloom piece.",
    emoji: "✨",
    inStock: true,
    rating: 4.8,
    reviews: 156,
    tags: ["panchamukha", "vilakku", "five-element", "brass"],
  },
  {
    id: "h5",
    slug: "copper-kalash",
    name: "Copper Kalash — Puja Pot with Lid",
    category: "home-decor",
    price: 999,
    description: "Pure copper Kalash (sacred vessel) for puja, 500ml capacity",
    longDescription: "The Kalash is an essential element of Vedic puja rituals, symbolizing the presence of all deities. This pure copper Kalash has a capacity of 500ml, comes with a lid adorned with a lotus motif, and includes mango leaves for immediate use.",
    emoji: "🏺",
    inStock: true,
    rating: 4.6,
    reviews: 289,
    tags: ["copper", "kalash", "puja", "ritual"],
  },
  {
    id: "h6",
    slug: "arunachala-painting-handmade",
    name: "Arunachala — Handpainted Sacred Landscape",
    category: "home-decor",
    price: 2799,
    badge: "Hand Painted",
    badgeColor: "#2D6A4F",
    description: "Original handpainted artwork of Arunachala hill at dawn, 12×16 inches",
    longDescription: "Each painting is an original artwork by artisans trained in traditional Thanjavur style, depicting the sacred Arunachala hill in the golden light of dawn. 12×16 inches on archival canvas. No two are identical. Comes framed in teak wood.",
    emoji: "🎨",
    inStock: true,
    rating: 4.9,
    reviews: 98,
    tags: ["painting", "arunachala", "art", "handmade", "framed"],
  },
];

export const categories = [
  { id: "all",        label: "All Products",  emoji: "🛕",  count: products.length },
  { id: "books",      label: "Books",         emoji: "📖",  count: products.filter(p => p.category === "books").length },
  { id: "rudraksha",  label: "Rudraksha",     emoji: "📿",  count: products.filter(p => p.category === "rudraksha").length },
  { id: "home-decor", label: "Home Decor",    emoji: "🪔",  count: products.filter(p => p.category === "home-decor").length },
];
